apiVersion: v1
kind: Service
metadata:
  name: {{ include "mydevops.fullname" . }}
  labels:
    {{- include "mydevops.labels" . | nindent 4 }}
  namespace: {{.Values.namespace}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mydevops.selectorLabels" . | nindent 4 }}
